version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: intellifinance_postgres
    environment:
      POSTGRES_DB: intellifinance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intellifinance_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: intellifinance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - intellifinance_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: intellifinance_backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/intellifinance
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - ENCRYPTION_KEY=your-encryption-key-32-chars-long
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - intellifinance_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: intellifinance_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - intellifinance_network

volumes:
  postgres_data:
  redis_data:

networks:
  intellifinance_network:
    driver: bridge
